# Generated by Django 3.0.4 on 2020-04-01 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_number",
                    models.IntegerField(default=0, help_text="Set to 0 if new player."),
                ),
                ("bank_balance", models.IntegerField(default=0)),
                (
                    "investment_balance",
                    models.IntegerField(default=0, verbose_name="Value of investments"),
                ),
                (
                    "property_balance",
                    models.IntegerField(default=0, verbose_name="Value of property"),
                ),
                (
                    "cc_balance",
                    models.IntegerField(default=0, verbose_name="Credit card balance"),
                ),
                ("mortgage_balance", models.IntegerField(default=0)),
                (
                    "wage",
                    models.IntegerField(
                        default=0, help_text="Paid fortnightly, 0 if unemployed."
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
