# Generated by Django 3.0.4 on 2020-04-10 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_number",
                    models.IntegerField(default=0, help_text="Set to 0 if new player."),
                ),
                ("bank_balance", models.IntegerField(default=0)),
                (
                    "investment_balance",
                    models.IntegerField(default=0, verbose_name="Value of investments"),
                ),
                (
                    "cc_current_month",
                    models.IntegerField(
                        default=0,
                        help_text="The portion of credit card balance that does not accrue interest.",
                        verbose_name="Current month's credit card balance",
                    ),
                ),
                (
                    "cc_overdue_balance",
                    models.IntegerField(
                        default=0,
                        help_text="The portion of credit card balance that accrues interest.",
                        verbose_name="Overdue credit card balance",
                    ),
                ),
                (
                    "wage",
                    models.IntegerField(
                        default=0, help_text="Paid fortnightly, 0 if unemployed."
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                ("price", models.IntegerField(default=0)),
                (
                    "owned_by",
                    models.ManyToManyField(
                        blank=True, related_name="items", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
