# Generated by Django 3.0.4 on 2020-04-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfgame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='cc_overdue_balance',
            field=models.IntegerField(default=0, help_text='The portion of credit card balance that accrues interest.', verbose_name='Overdue credit card balance'),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='cc_balance',
            field=models.IntegerField(default=0, help_text='The portion of credit card balance that does not accrue interest.', verbose_name='Credit card balance'),
        ),
    ]
